language: node_js

node_js:
  - '10.15.3'
  
before_install:
  - npm install -g yarn@1.16.0

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
