services:
  bot:
    container_name: gamefeeder
    image: ghcr.io/gamefeeder/gamefeeder/gamefeeder:latest
    volumes:
      - ./config/api_config.json:/app/config/api_config.json
      - ./config/updater_config.json:/app/config/updater_config.json
      - ./data:/app/data
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
