name: ci-flow

on:
  pull_request:
  # Also run it on pushes for main, for the badges
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4.1.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check for code style & formatting
        run: npm run lint

      - name: Run typescript compiler
        run: npm run build

      - name: Check for circular dependencies
        run: npx madge --circular --extensions js ./dist

      - name: Run the tests
        run: npm run test

        env:
          CI: true
