name: ci-flow

on:
  pull_request:
  # Also run it on pushes for main, for the badges
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.17.2]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Check for code style & formatting
        run: yarn lint

      - name: Run typescript compiler
        run: yarn build

      - name: Check for circular dependencies
        run: npx madge --circular --extensions js ./dist

      - name: Run the tests
        run: yarn test

        env:
          CI: true
