name: ci-flow

on: [pull_request]

jobs:
  CI:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Build the workspace image
        run: docker build . --target=workspace -t workspace

      - name: Check for code style & formatting
        run: docker run init workspace yarn lint

      - name: Run typescript compiler
        run: docker run init workspace yarn build

      - name: Run the tests
        run: docker run init workspace yarn test

        env:
          CI: true
