name: tag-flow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # This is needed for creating releases/tags
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      - name: Get current version
        id: get_version
        run: echo "gamefeeder_version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin refs/tags/v${{ steps.get_version.outputs.gamefeeder_version }} | grep -q v${{ steps.get_version.outputs.gamefeeder_version }}; then
            echo "Tag v${{ steps.get_version.outputs.gamefeeder_version }} already exists, skipping tag creation"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag v${{ steps.get_version.outputs.gamefeeder_version }} does not exist, will create"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Create Git Tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${{ steps.get_version.outputs.gamefeeder_version }} -m "Release v${{ steps.get_version.outputs.gamefeeder_version }}"
          git push origin v${{ steps.get_version.outputs.gamefeeder_version }}
      - name: Create GitHub Release
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.get_version.outputs.gamefeeder_version }}
          tag_name: v${{ steps.get_version.outputs.gamefeeder_version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
